import{useMemo,useState}from"react";import{CheckCircle2,Clock3,Edit3,Plus,Trash2}from"lucide-react";import type{Dispatch,SetStateAction}from"react";import type{AppData,StudySession}from"../types";import{getChapter,getPaper,getSubject}from"../data/syllabus";import{formatDuration,formatTime,localDate,minutesBetween,uid}from"../lib/storage";import{Field,StudyFields}from"../components/StudyFields";import{Empty,SessionItem,SectionHead}from"../components/UI";
export default function DailyLog({data,setData}:{data:AppData;setData:Dispatch<SetStateAction<AppData>>}){
 const[date,setDate]=useState(localDate()),[subjectId,setSubject]=useState(""),[paperId,setPaper]=useState(""),[chapterId,setChapter]=useState(""),[start,setStart]=useState("19:00"),[end,setEnd]=useState("20:00"),[topic,setTopic]=useState(""),[editingId,setEditingId]=useState<string|null>(null),[message,setMessage]=useState("");
 const mins=useMemo(()=>minutesBetween(start,end),[start,end]),matches=data.plans.filter(p=>p.date===date&&p.subjectId===subjectId&&p.paperId===paperId&&p.chapterId===chapterId);
 const reset=()=>{setSubject("");setPaper("");setChapter("");setStart("19:00");setEnd("20:00");setTopic("");setEditingId(null)};
 const submit=()=>{if(!subjectId||!paperId||!chapterId){setMessage("Choose a subject and chapter.");return}if(!start||!end||mins<=0){setMessage("Choose a valid time range.");return}const now=new Date().toISOString();setData(old=>editingId?({...old,sessions:old.sessions.map(s=>s.id===editingId?{...s,date,subjectId,paperId,chapterId,start,end,duration:mins,topic,updatedAt:now}:s)}):({...old,sessions:[...old.sessions,{id:uid(),date,subjectId,paperId,chapterId,start,end,duration:mins,topic,createdAt:now,updatedAt:now}]}));setMessage(editingId?"Session updated.":"Study session saved.");setEditingId(null);setTimeout(()=>setMessage(""),1800)};
 const edit=(s:StudySession)=>{setDate(s.date);setSubject(s.subjectId);setPaper(s.paperId);setChapter(s.chapterId);setStart(s.start);setEnd(s.end);setTopic(s.topic);setEditingId(s.id);window.scrollTo({top:0,behavior:"smooth"})};
 const remove=(id:string)=>{if(window.confirm("Delete this study session?"))setData(old=>({...old,sessions:old.sessions.filter(s=>s.id!==id)}))};
 const updateProgress=(id:string,value:number)=>setData(old=>({...old,plans:old.plans.map(p=>p.id===id?{...p,progress:value,status:value===100?"completed":value?"in-progress":"not-started",updatedAt:new Date().toISOString()}:p)}));
 return <div className="stack"><section className="card form-card"><div className="section-head"><div><span className="eyebrow">FAST ENTRY</span><h2>{editingId?"Edit study session":"Add study session"}</h2><p className="muted">Select → select → choose time → optional topic → save.</p></div>{editingId&&<button className="text-btn" onClick={reset}>Cancel</button>}</div>
 <div className="form-grid"><Field label="Date"><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><StudyFields subjectId={subjectId} setSubject={setSubject} paperId={paperId} setPaper={setPaper} chapterId={chapterId} setChapter={setChapter}/><Field label="From"><input type="time" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="To"><input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></Field><div className={"duration "+(mins<=0?"invalid":"")}><span>Duration</span><strong>{mins>0?formatDuration(mins):"Invalid time range"}</strong><small>{mins>0?"Calculated automatically. End time may be later that day or after midnight.":"Pick a different end time."}</small></div><Field label="What I studied (optional)"><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. Newton's laws and applications"/></Field></div>
 {matches.length>0&&<div className="target-panel"><div className="target-copy"><div className="target-icon"><CheckCircle2 size={18}/></div><div><b>Planned target found</b><span>{matches.length===1?matches[0].topic||getChapter(subjectId,paperId,chapterId)?.name:`${matches.length} planned targets for this chapter`}</span><small>Progress follows the selected date, subject, and chapter. The topic is a flexible note.</small></div></div><div className="targets">{matches.map(p=><div className="target-line" key={p.id}><span>{p.topic||"Chapter target"}</span><div className="pct-buttons">{[0,25,50,75,100].map(n=><button key={n} className={p.progress===n?"selected":""} onClick={()=>updateProgress(p.id,n)}>{n}%</button>)}</div><b>{p.progress===100?"✓ Completed":p.progress+"% complete"}</b></div>)}</div></div>}
 <div className="form-actions"><button className="primary" onClick={submit}>{editingId?"Update session":"Save study session"}</button>{message&&<span className={message.includes("saved")||message.includes("updated")?"save-note":"error-note"}>{message}</span>}</div>
 </section>
 <section className="card"><SectionHead eyebrow="RECENT & HISTORY" title="Study log"/>{data.sessions.length?<div className="session-list">{data.sessions.slice().sort((a,b)=>(b.date+b.start).localeCompare(a.date+a.start)).map(s=><div className="history-row" key={s.id}><SessionItem s={s}/><div className="row-actions"><button className="icon-btn" onClick={()=>edit(s)} aria-label="Edit"><Edit3 size={17}/></button><button className="icon-btn danger" onClick={()=>remove(s.id)} aria-label="Delete"><Trash2 size={17}/></button></div></div>)}</div>:<Empty icon={Clock3} title="Your study log is empty" text="Your first saved session will appear here."/>}</section>
 </div>
}