import{useState}from"react";import{CalendarDays,Edit3,Trash2}from"lucide-react";import type{Dispatch,SetStateAction}from"react";import type{AppData,StudyPlan}from"../types";import{localDate,uid}from"../lib/storage";import{Field,StudyFields}from"../components/StudyFields";import{Empty,PlanItem,SectionHead}from"../components/UI";
export default function Planning({data,setData}:{data:AppData;setData:Dispatch<SetStateAction<AppData>>}){
 const[d,setD]=useState(localDate()),[subjectId,setSubject]=useState(""),[paperId,setPaper]=useState(""),[chapterId,setChapter]=useState(""),[topic,setTopic]=useState(""),[progress,setProgress]=useState(0),[reminder,setReminder]=useState(false),[time,setTime]=useState("20:00"),[repeat,setRepeat]=useState<"none"|"hourly">("none"),[editingId,setEditingId]=useState<string|null>(null),[message,setMessage]=useState("");
 const submit=()=>{if(!subjectId||!paperId||!chapterId){setMessage("Choose a subject and chapter.");return}const now=new Date().toISOString(),old=data.plans.find(p=>p.id===editingId);const plan:StudyPlan={id:editingId||uid(),date:d,subjectId,paperId,chapterId,topic,progress,status:progress===100?"completed":progress?"in-progress":"not-started",reminder:{enabled:reminder,time,repeat},createdAt:old?.createdAt||now,updatedAt:now};setData(x=>({...x,plans:editingId?x.plans.map(p=>p.id===editingId?plan:p):[...x.plans,plan]}));setMessage(editingId?"Plan updated.":"Plan added.");setEditingId(null);setTimeout(()=>setMessage(""),1800)};
 const edit=(p:StudyPlan)=>{setD(p.date);setSubject(p.subjectId);setPaper(p.paperId);setChapter(p.chapterId);setTopic(p.topic);setProgress(p.progress);setReminder(p.reminder.enabled);setTime(p.reminder.time||"20:00");setRepeat(p.reminder.repeat);setEditingId(p.id);window.scrollTo({top:0,behavior:"smooth"})};
 const remove=(id:string)=>{if(window.confirm("Delete this study plan?"))setData(x=>({...x,plans:x.plans.filter(p=>p.id!==id)}))};
 const cancel=()=>{setEditingId(null);setSubject("");setPaper("");setChapter("");setTopic("");setProgress(0);setReminder(false)};
 return <div className="stack"><section className="card form-card"><div className="section-head"><div><span className="eyebrow">FUTURE TARGETS</span><h2>{editingId?"Edit plan":"Plan study"}</h2><p className="muted">Plan by structured syllabus fields; keep the topic flexible.</p></div>{editingId&&<button className="text-btn" onClick={cancel}>Cancel</button>}</div>
 <div className="form-grid"><Field label="Date"><input type="date" value={d} onChange={e=>setD(e.target.value)}/></Field><StudyFields subjectId={subjectId} setSubject={v=>{setSubject(v);setPaper("");setChapter("")}} paperId={paperId} setPaper={v=>{setPaper(v);setChapter("")}} chapterId={chapterId} setChapter={setChapter}/><Field label="Topic (manual)"><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. Newton's Laws and applications"/></Field><Field label="Progress"><div className="progress-control"><input type="range" min="0" max="100" step="25" value={progress} onChange={e=>setProgress(Number(e.target.value))}/><strong>{progress}%</strong></div></Field><Field label="Reminder"><div className="inline-control"><input type="checkbox" checked={reminder} onChange={e=>setReminder(e.target.checked)}/><span>Enable browser reminder</span></div></Field>{reminder&&<><Field label="Reminder time"><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></Field><Field label="Repeat"><select value={repeat} onChange={e=>setRepeat(e.target.value as "none"|"hourly")}><option value="none">None</option><option value="hourly">Every hour while the app is active</option></select></Field></>}</div>
 <div className="form-actions"><button className="primary" onClick={submit}>{editingId?"Update plan":"Add plan"}</button>{message&&<span className={message.includes("added")||message.includes("updated")?"save-note":"error-note"}>{message}</span>}</div></section>
 <section className="card"><SectionHead eyebrow="PLANNED TARGETS" title={data.plans.length+" plans"}/>{data.plans.length?<div className="plan-list">{data.plans.slice().sort((a,b)=>(a.date+a.updatedAt).localeCompare(b.date+b.updatedAt)).map(p=><div className="history-row" key={p.id}><div className="plan-with-date"><span className="date-pill">{p.date}</span><PlanItem p={p}/></div><div className="row-actions"><button className="icon-btn" onClick={()=>edit(p)} aria-label="Edit"><Edit3 size={17}/></button><button className="icon-btn danger" onClick={()=>remove(p.id)} aria-label="Delete"><Trash2 size={17}/></button></div></div>)}</div>:<Empty icon={CalendarDays} title="No plans yet" text="Plan tomorrow's study and it will surface in your daily workflow."/>}</section>
 </div>
}
